image: haskell:8

services:
  - docker:dind

build:
  stage: build
  script:
    - cabal sandbox init
    - cabal update
    - cabal install --only-dependencies
    # - runhaskell Setup.hs configure --user
    # - runhaskell Setup.hs build
    - make
