image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - apk add --update ghc make curl
    - curl -sSL https://get.haskellstack.org | sh
    - make setup build
